CREATE TABLE IF NOT EXISTS MEMBER (
    MEMBER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(200) NOT NULL,
    NICKNAME VARCHAR(50) NOT NULL,
    REG_DATE TIMESTAMP NOT NULL,
    MOD_DATE TIMESTAMP NOT NULL
    );