CREATE TABLE IF NOT EXISTS BOARD (
    BOARD_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(100) NOT NULL,
    CONTENT TEXT NOT NULL,
    AUTHOR VARCHAR(40) NOT NULL,
    REG_DATE TIMESTAMP NOT NULL,
    MOD_DATE TIMESTAMP NOT NULL
);